-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 09:10:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mushu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mushu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mushu` DEFAULT CHARACTER SET utf8 ;
USE `mushu` ;

-- -----------------------------------------------------
-- Table `mushu`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mushu`.`funcionario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NULL,
  `apelido` VARCHAR(45) NULL,
  `sexo` VARCHAR(1) NULL,
  `admissao` DATE NULL,
  `nascimento` DATE NULL,
  `cargo` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  `senha` VARCHAR(45) NULL,
  `vendedor` TINYINT(1) NULL,
  `tecnico` TINYINT(1) NULL,
  `liberado` TINYINT(1) NULL,
  `email` VARCHAR(125) NULL,
  `inativo` TINYINT(1) NULL,
  `gestor` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mushu`.`senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mushu`.`senha` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `link` VARCHAR(150) NULL,
  `login` VARCHAR(150) NULL,
  `senha` VARCHAR(150) NULL,
  `vendedor` TINYINT(1) NULL,
  `tecnico` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mushu`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mushu`.`tarefa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_funcionario_delegante` INT UNSIGNED NULL,
  `id_funcionario_delegado` INT UNSIGNED NULL,
  `prazo` DATETIME NULL,
  `descricao` TEXT NULL,
  `concluido` DATETIME NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tarefa_delegante`
    FOREIGN KEY (`id_funcionario_delegante`)
    REFERENCES `mushu`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefa_delegado`
    FOREIGN KEY (`id_funcionario_delegado`)
    REFERENCES `mushu`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tarefa_delegante_idx` ON `mushu`.`tarefa` (`id_funcionario_delegante` ASC);

CREATE INDEX `fk_tarefa_delegado_idx` ON `mushu`.`tarefa` (`id_funcionario_delegado` ASC);


-- -----------------------------------------------------
-- Table `mushu`.`liberacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mushu`.`liberacao` (
  `funcionario_id` INT UNSIGNED NOT NULL,
  `ferramenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ferramenta`, `funcionario_id`),
  CONSTRAINT `fk_liberacao_funcionario`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mushu`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_liberacao_funcionario_idx` ON `mushu`.`liberacao` (`funcionario_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mushu`.`funcionario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mushu`;
INSERT INTO `mushu`.`funcionario` (`id`, `nome`, `apelido`, `sexo`, `admissao`, `nascimento`, `cargo`, `cpf`, `senha`, `vendedor`, `tecnico`, `liberado`, `email`, `inativo`, `gestor`) VALUES (1, 'Gerente para Construção', 'Gerente', 'M', '2017-01-01', '1995-10-27', 'Gerente', '08027280907', '202cb962ac59075b964b07152d234b70', 1, 1, 1, 'bruno@idealmotopecas.com', 0, 1);

COMMIT;

